#!/bin/sh
# Ensure Node is on PATH in Git Bash (Windows)
if [ -x "/c/Program Files/nodejs/node.exe" ]; then
 PATH="/c/Program Files/nodejs:$PATH"
fi

# go to the project root (one level up from .husky)
cd "$(dirname "$0")/.." || exit 1

echo "Lint-staged..."
./node_modules/.bin/lint-staged --allow-empty || exit 1

echo "Typecheck..."
./node_modules/.bin/tsc --noEmit || exit 1

exit 0
